version: '3.8'

services:
  api:
    build: api
    ports: 
      - "3000:3000"
    depends_on:
      - cache


  cache:
    image: redis:6.2
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --loglevel warning
    volumes:
      - ./cache:/data